/**
 * Constants for Rule Import/Export
 */

export const IMPORT_ERROR_CODES = {
  INVALID_FORMAT: 'IMPORT_INVALID_FORMAT',
  VALIDATION_FAILED: 'IMPORT_VALIDATION_FAILED',
  DUPLICATE_ID: 'IMPORT_DUPLICATE_ID',
  MISSING_PROGRAM: 'IMPORT_MISSING_PROGRAM',
  TEST_FAILED: 'IMPORT_TEST_FAILED',
  VERSION_CONFLICT: 'IMPORT_VERSION_CONFLICT',
  CHECKSUM_MISMATCH: 'IMPORT_CHECKSUM_MISMATCH',
  DATABASE_ERROR: 'IMPORT_DATABASE_ERROR',
} as const;

export const PROGRAM_IDS = {
  SNAP_FEDERAL: 'snap-federal',
  SSI_FEDERAL: 'ssi-federal',
} as const;
